export const ALPHA_DISTRIBUTION = {
  productName: "T3 Code Alpha",
  desktopAppId: "com.theblankclub.t3code.alpha",
  desktopProtocolScheme: "t3code-alpha",
  desktopHomeDirName: ".t3-alpha",
  desktopUserDataDirName: "t3code-alpha",
  desktopPackageName: "t3code-alpha",
  macReleaseSigningIdentity: "T3 Code Alpha Release Signing",
  macReleaseSigningCertificateSha1: "A3FE7063335600A78DDB3634CF76D5E1EF6D9645",
  linuxExecutableName: "t3code-alpha",
  linuxDesktopEntryName: "t3code-alpha.desktop",
  linuxUrlHandlerDesktopEntryName: "t3code-alpha-url-handler.desktop",
  linuxWmClass: "t3code-alpha",
  artifactName: "T3-Code-Alpha-${version}-${arch}.${ext}",
  serverPackageName: "t3code-alpha",
  serverBinaryName: "t3-alpha",
  serverNpmDistTag: "latest",
  serverHomeDirName: ".t3-alpha",
  serverSystemdUnitName: "t3code-alpha.service",
} as const;
